font: 
  normal:
    family: Roboto Mono Nerd Font
    style: Medium #Light #Nerd Font Complete
  bold:
    family: Roboto Mono Nerd Font
    style: Bold #Nerd Font Complete
  italic:
    family: Roboto Mono Nerd Font
    style: Italic #Nerd Font Complete

  offset:
    x: 0
    y: 2
  glyph_offset:
    x: 0
    y: 0
